### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by thenavz6**
## Context
[Corresponding Pivotal Tracker story](https://www.pivotaltracker.com/story/show/175033790)

### Code Refactor
- Added `react-router-dom` to the project to handle private and public pages
- Added `PrivateRoute` for private pages. These cannot be visited without authentication
- Moved the main app rendering logic to `components/Pages/Dashboard.tsx`

### Authentication
- Authentication logic handled in `./Login.tsx`
- Authentication Page in `components/Pages/Login.tsx`
- After login, auth token is stored in localstorage["token"]
- Added basic (ugly) login and logout buttons

### CODE REVIEW

**Comment by CarlinWilliamson** [comment]
So I just gave this a go. And I found myself on a page with the text `INVALID_CLIENT: Invalid client`
Going back and clicking on the login button again sends me to the same page (have to clear my cache to get to the login screen again)

**Comment by thenavz6** [comment]
> So I just gave this a go. And I found myself on a page with the text `INVALID_CLIENT: Invalid client`
> Going back and clicking on the login button again sends me to the same page (have to clear my cache to get to the login screen again)

Ah okay, so this has to do with the build rules. In our local environments, we each have a file called .env.local that stores the clientID and clientSecret. When the app is built, however, this file is ignored, so the app has no reference of the clientID.

If you got this error while testing on your local machine, add the attached file to the root directory of your project and try again
[.env.local.txt](https://github.com/Splitify/splitify/files/5388479/default.env.local.txt)

**Review by featherbear — APPROVED** [review]
~lgtm~

**Review by featherbear — CHANGES_REQUESTED** [review]
Components can be refactored for easier integration with future developments

**Review by featherbear — APPROVED** [review]

**Review by CarlinWilliamson — APPROVED** [review]
lgtm

**Pull request merged**
