### PR TITLE
Genre splitting

### PR DESCRIPTION
**Pull request by z5160345**
## Context

https://www.pivotaltracker.com/story/show/175195587

## Description 💬
Need help with adding valid track data to subplaylists. Right now the implementation is that a subplaylist takes in the entire track data of masterplaylist and conditionally renders tracks based on which genres are selected. Right now subplaylists take in an empty track object
Added in functionality to split the master playlist on genres.
Added in an autofill bar to help the users navigate the genres

## Checklist ✅:

- [x] I assigned the story to myself on Pivotal Tracker before I started working on this
- [x] Added a link to the user story context
- [x] Added a description of my changes
- [x] Assigned at least two reviewers

### CODE REVIEW

**Comment by CarlinWilliamson** [comment]
Maybe don't assign reviewers to a draft PR. Took me a minute to figure out it wasn't quite ready yet

**Comment by z5160345** [comment]
> Maybe don't assign reviewers to a draft PR. Took me a minute to figure out it wasn't quite ready yet

Yep, unassigned

**Review by thenavz6 — APPROVED** [review]
lgtm

**Review by CarlinWilliamson — APPROVED** [review]
lgtm thanks for doing the merge... XD

**Pull request merged**
