### PR TITLE
Manually reorder tracks in sub-playlist

### PR DESCRIPTION
**Pull request by featherbear**
## Context

[Corresponding Pivotal Tracker story](https://www.pivotaltracker.com/story/show/175033796)

## Description 💬

* \+ package:`react-beautiful-dnd`
* requires change to `TrackEntry`, to move the `TrackRow` and `TrackCell` outside
* Put track filtering results into a state

## Checklist ✅:

- [x] I assigned the story to myself on Pivotal Tracker before I started working on this
- [x] Added a link to the user story context
- [x] Added a description of my changes
- [x] Assigned at least two reviewers

### CODE REVIEW

**Review by CarlinWilliamson — DISMISSED** [review]
Could we get a drag indicator so the user knows they're dragable? https://material-ui.com/components/material-icons/

It does a flickering thing when it moves the tracks around. This might be too difficult to solve

Do you know if this will integrate well with track information?

**Comment by featherbear** [comment]
> Could we get a drag indicator so the user knows they're dragable? https://material-ui.com/components/material-icons/
>

Yep can do, will make provisions for this later


> It does a flickering thing when it moves the tracks around. This might be too difficult to solve
> 

I observed this too; I'm not entirely sure what's causing it.  
I did a quick timing log before, and there seems to be a 100ms delay between the `onDragEnd` event (`react-beautiful-dnd`) and the re-render. I might investigate forcing a state update or likewise;

But for now I'm labelling this as a **won't fix**; unless you think it's crucial to be fixed

> Do you know if this will integrate well with track information?

🙃

It should be fine if you throw your track info stuff into TrackEntry

**Comment by featherbear** [comment]
I'm also going to revert my changes of moving `TableRow` and `TableCell` out of `TrackEntry`, as the previous design feels better now that I think about it.
Will **draft** this PR until ready for review

**Review by CarlinWilliamson — DISMISSED** [review]
Couple things.

- Drag Icons please https://material-ui.com/components/material-icons/
- The bubble is kindof redundant now if the numbers move with the slider (See image below)
- Does this PR encompass drag and drop between subplaylists? doesn't seem to work for me (also hasn't been started or finished on pivotal)

[image.](https://imgur.com/a/td0NTlJ)

**Comment by featherbear** [comment]
>
>     * Drag Icons please https://material-ui.com/components/material-icons/

Where would you propose to put the icon (`DragHandle` - `=`)?
The left side will be used for the checkboxes when selecting, so maybe the right side?

> 
>     * The bubble is kindof redundant now if the numbers move with the slider (See image below)

I'll make changes to that, mistake on my part when porting
 
>     * Does this PR encompass drag and drop between subplaylists? doesn't seem to work for me (also hasn't been started or finished on pivotal)

Nup, that functionality will be for a different PR.
I want to clear this one before the PR gets too big

- Image did not load ( :

**Comment by CarlinWilliamson** [comment]
> > ```
> > * Drag Icons please https://material-ui.com/components/material-icons/
> > ```
> 
> Where would you propose to put the icon (`DragHandle` - `=`)?
> The left side will be used for the checkboxes when selecting, so maybe the right side?
> 

Right side seems sensible

> > ```
> > * The bubble is kindof redundant now if the numbers move with the slider (See image below)
> > ```
> 
> I'll make changes to that, mistake on my part when porting
> 
> > ```
> > * Does this PR encompass drag and drop between subplaylists? doesn't seem to work for me (also hasn't been started or finished on pivotal)
> > ```
> 
> Nup, that functionality will be for a different PR.
> I want to clear this one before the PR gets too big
> 
> * Image did not load ( :
It's now just a link. either I'm too dumb or github didn't want to embed

**Comment by featherbear** [comment]
Note: The drag handle icon element consumes a lot of space. I propose a change from the current `Table` layout to a `List` component, which has better support for what we are attempting to do

**Review by CarlinWilliamson — APPROVED** [review]
lgtm

**Review by z5160345 — APPROVED** [review]
lgtm

**Pull request merged**
