### PR TITLE
Manually move tracks between sub-playlists

### PR DESCRIPTION
**Pull request by featherbear**
## Context

[Corresponding Pivotal Tracker story](https://www.pivotaltracker.com/story/show/175033767)

## Description 💬

Updated track reordering functionality to allow inter-playlist track management

## Checklist ✅:

- [x] I assigned the story to myself on Pivotal Tracker before I started working on this
- [x] Added a link to the user story context
- [x] Added a description of my changes
- [x] Assigned at least two reviewers

### CODE REVIEW

**Review by CarlinWilliamson — CHANGES_REQUESTED** [review]
I'm getting a `TypeError: Cannot read property 'id' of undefined`

To recreate. Have two sub-playlists with seperate genres.
Drag a song from playlist B to the **end** of playlist A

**Comment by featherbear** [comment]
> 
> 
> I'm getting a `TypeError: Cannot read property 'id' of undefined`
> 
> To recreate. Have two sub-playlists with seperate genres.
> Drag a song from playlist B to the **end** of playlist A

Ah thanks, I'll get onto that.
Posting error trace for reference

image

**Comment by z5160345** [comment]
Seems like right now it doesnt allow user to drag song to the very bottom of a track

**Comment by featherbear** [comment]
Track ordering issue regarding adding an item to the end of the playlist should be fixed, please have a look at it now 💯

**Review by z5160345 — APPROVED** [review]
lftm

**Review by CarlinWilliamson — APPROVED** [review]
lgtm

**Pull request merged**
