### PR TITLE
View unused

### PR DESCRIPTION
**Pull request by CarlinWilliamson**
## Context

[Corresponding Pivotal Tracker story](https://www.pivotaltracker.com/story/show/175033792)

## Description 💬
Adds a toggle button for hiding tracks which appear in a subplaylist
and suggestions for which genre should be used next

## Checklist ✅:

- [x] I assigned the story to myself on Pivotal Tracker before I started working on this
- [x] Added a link to the user story context
- [x] Added a description of my changes
- [x] Assigned at least two reviewers

### CODE REVIEW

**Comment by CarlinWilliamson** [comment]
Originally the story included showing unused audio features too but I figure it's already obvious enough with our UI (you can look at what sliders you have up and see which values you've left out)

**Comment by featherbear** [comment]
image

Typo!

**Comment by CarlinWilliamson** [comment]
> image
> 
> Typo!

What you call a typo. I call an alliteration!

**Review by z5160345 — APPROVED** [review]
lgtm

**Review by zacharygilmour17 — APPROVED** [review]
looks good

**Pull request merged**
