### PR TITLE
Genre api lastfm

### PR DESCRIPTION
**Pull request by CarlinWilliamson**
## Context

[Corresponding Pivotal Tracker story](https://www.pivotaltracker.com/story/show/175570805)

## Description 💬
Use genre data from last.fm (which is track specific instead of artist specific)

## Checklist ✅:

- [x] I assigned the story to myself on Pivotal Tracker before I started working on this
- [x] Added a link to the user story context
- [x] Added a description of my changes
- [x] Assigned at least two reviewers

### CODE REVIEW

**Review by featherbear — CHANGES_REQUESTED** [review]
Would you be able to integrate the code that uses `<Accumulumatorinator>.requestURL` function, to use the `<Accumulumatorinator>.request` function? I prefer for the Accumulumatorinator to be unopinionated, and `requestURL` is referenced only once

The change in your `requestURL` function can be integrated into the callback for your `GenreAccumulator`

--

Also, could you move the genre whitelist into a separate file, and have it imported?

**Comment by featherbear** [comment]
@CarlinWilliamson Change the API endpoint to `https` - doesn't work on the PR preview (and deploy) due to HTTP(S) mixed content issues.

**Review by featherbear — APPROVED** [review]
lgtm 

niceeeeeeee

**Review by z5160345 — APPROVED** [review]
Thanks, was worried that the Spotify genres were a bit janky

**Pull request merged**
