### PR TITLE
Auth UI

### PR DESCRIPTION
**Pull request by featherbear**
## Context

[Corresponding Pivotal Tracker story](https://www.pivotaltracker.com/story/show/175298287)

## Description 💬

Added styling for the authentication login page

## Checklist ✅:

- [x] I assigned the story to myself on Pivotal Tracker before I started working on this
- [x] Added a link to the user story context
- [x] Added a description of my changes
- [x] Assigned at least two reviewers

### CODE REVIEW

**Review by thenavz6 — CHANGES_REQUESTED** [review]
The preview build is failing at the moment. Need to change clientID to the new one and add https://deploy-preview-8--splitify-preview.netlify.app/login to the whitelist on Spotify App Dashboard

**Comment by featherbear** [comment]
@thenavz6 Client ID has been updated, and Redirect URI has been added to the whitelist

**Review by CarlinWilliamson — APPROVED** [review]
lgtm

**Review by thenavz6 — APPROVED** [review]
lgtm

**Pull request merged**
